const ExcelJS=require('exceljs')
const {getCurrentUid}=require('../common/auth')
const {userCollection,teamMemberCollection,cusTable,logTable,dbCmd}=require('../common/db')
const SALES=[{label:'售前沟通',subNodes:[{label:'首次接洽'},{label:'寒暄'},{label:'KYC'}]},{label:'首次销售面谈',subNodes:[{label:'寒暄'},{label:'理念沟通'},{label:'异议处理'}]},{label:'二次销售面谈',subNodes:[{label:'回顾'},{label:'方案阐述'},{label:'异议处理'}]},{label:'缔结',subNodes:[{label:'寒暄'},{label:'异议处理'},{label:'最终缔结'}]}]
const RECRUIT=[{label:'项链增员',subNodes:[{label:'首次接洽'},{label:'软性Eop'},{label:'挖过去夸现在'}]},{label:'吸引面谈',subNodes:[{label:'理念Eop'},{label:'展未来扣项链'},{label:'异议处理'}]},{label:'事业面谈',subNodes:[{label:'硬性Eop'},{label:'回顾'},{label:'一面'}]},{label:'甄选流程',subNodes:[{label:'二面'},{label:'三面'},{label:'入训岗前简介'}]}]
const getWeekRanges=(nowMs)=>{const n=new Date(nowMs);const d=new Date(n.getFullYear(),n.getMonth(),n.getDate(),0,0,0,0);const day=d.getDay();const diff=(day+6)%7;const thisStart=d.getTime()-diff*86400000;return{thisStart,nextStart:thisStart+7*86400000,lastStart:thisStart-7*86400000}}
const toTimeMs=(t)=>{if(t==null)return 0;if(typeof t==='number')return t;if(typeof t==='string'){const n=Number(t);return Number.isFinite(n)?n:0}if(t instanceof Date)return t.getTime();if(typeof t==='object'){const ts=t&&t.getTime&&t.getTime();if(typeof ts==='number'&&Number.isFinite(ts))return ts;const d=t.date;if(d instanceof Date)return d.getTime();const v=t.value;if(typeof v==='number')return v}return 0}
const getNodesByKind=(kind)=>kind==='recruit'?RECRUIT:SALES
const getRowsByKind=(kind)=>{const rows=[];getNodesByKind(kind).forEach(n=>{rows.push({key:n.label,label:n.label});(n.subNodes||[]).forEach(s=>rows.push({key:`${n.label}-${s.label}`,label:`${n.label}-${s.label}`}))});return rows}
const normalizeNodeKey=(v)=>{v=String(v||'').trim();if(!v)return'__UNSET__';if(v==='活跃'||v==='挂起'||v==='关单')return'';return v}
const formatDateOnly=(ms)=>{const d=new Date(ms);const p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
const formatDateTime=(ms)=>{const d=new Date(ms);const p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`}
async function ensureAccess({uid,targetUid}){const {data:users}=await userCollection.where({_id:uid}).field({role:true}).limit(1).get();const roles=(users&&users[0]&&Array.isArray(users[0].role))?users[0].role:[];if(roles.includes('admin')||uid===targetUid)return{ok:true};const leaderRes=await teamMemberCollection.where({userId:uid,status:'joined',role:'leader'}).limit(1).get();const leader=leaderRes?.data&&leaderRes.data[0];if(!leader)return{ok:false,errCode:'permission-denied',errMsg:'无权限'};const targetRes=await teamMemberCollection.where({userId:targetUid,teamId:leader.teamId,status:'joined'}).limit(1).get();return targetRes?.data&&targetRes.data.length?{ok:true}:{ok:false,errCode:'permission-denied',errMsg:'无权限'}}
async function loadStats({targetUid,kind}){const {thisStart,nextStart,lastStart}=getWeekRanges(Date.now());const type=kind==='recruit'?'增员':'客户';const logRes=await logTable.where({create_by:targetUid}).orderBy('createTime','desc').limit(2000).field({_id:true,cus_id:true,previousNodeStatus:true,currentNodeStatus:true,nodeRemark:true,createTime:true}).get();const logs=(logRes?.data||[]).map(l=>{const ms=toTimeMs(l.createTime);const wk=ms>=thisStart&&ms<nextStart?'this':ms>=lastStart&&ms<thisStart?'last':'';return wk?Object.assign({},l,{__weekKey:wk}):null}).filter(Boolean);const cusIds=Array.from(new Set(logs.map(l=>String(l.cus_id||'')).filter(Boolean)));if(!cusIds.length)return{logs:[],cusMap:{}};const cusRes=await cusTable.where(dbCmd.and([{_id:dbCmd.in(cusIds)},{create_by:targetUid},{type},{status:'活跃'}])).field({_id:true,name:true}).get();const cusMap={};(cusRes?.data||[]).forEach(c=>{cusMap[String(c._id)]={_id:c._id,name:c.name}});return{logs,cusMap}}
function buildSummary({kind,logs,cusMap}){const rows=getRowsByKind(kind);const rowSet=new Set(rows.map(r=>r.key));const countMap={this:{},last:{}};const detailMap={this:{},last:{}};rows.forEach(r=>{countMap.this[r.key]=0;countMap.last[r.key]=0;detailMap.this[r.key]=[];detailMap.last[r.key]=[]});logs.forEach(l=>{const cusId=String(l.cus_id||'');const cus=cusMap[cusId];if(!cus)return;const wk=l.__weekKey==='last'?'last':'this';const nodeKey=normalizeNodeKey(l.currentNodeStatus);if(!nodeKey||!rowSet.has(nodeKey))return;countMap[wk][nodeKey]=Number(countMap[wk][nodeKey]||0)+1;detailMap[wk][nodeKey].push({cusId,name:String(cus.name||''),previousNodeStatus:String(l.previousNodeStatus||''),currentNodeStatus:String(l.currentNodeStatus||''),remark:String(l.nodeRemark||'').trim(),createTime:toTimeMs(l.createTime)})});return{rows,countMap,detailMap}}
async function makeBuffer({kind,targetUid,rows,countMap,detailMap}){const kindLabel=kind==='recruit'?'增员':'销售（客户）';const wb=new ExcelJS.Workbook();wb.creator='xuanshang';wb.created=new Date();const sum=wb.addWorksheet('统计汇总');const detail=wb.addWorksheet('变更明细');const header=['指标'].concat(rows.map(r=>r.label));sum.mergeCells(1,1,1,header.length);sum.getCell(1,1).value=`${kindLabel}统计（导出日期：${formatDateOnly(Date.now())}）`;sum.getCell(1,1).font={bold:true,size:16};sum.getCell(1,1).alignment={vertical:'middle',horizontal:'center'};sum.addRow(header);sum.addRow(['本周次数'].concat(rows.map(r=>Number(countMap.this[r.key]||0))));sum.addRow(['上周次数'].concat(rows.map(r=>Number(countMap.last[r.key]||0))));sum.addRow(['总计'].concat(rows.map(r=>Number(countMap.this[r.key]||0)+Number(countMap.last[r.key]||0))));sum.getRow(2).font={bold:true};sum.getRow(2).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF1F5F9'}};sum.columns=[{width:14}].concat(rows.map(()=>({width:18})));[2,3,4,5].forEach(n=>sum.getRow(n).eachCell(cell=>{cell.alignment={vertical:'middle',horizontal:'center'};cell.border={top:{style:'thin',color:{argb:'FFE2E8F0'}},left:{style:'thin',color:{argb:'FFE2E8F0'}},bottom:{style:'thin',color:{argb:'FFE2E8F0'}},right:{style:'thin',color:{argb:'FFE2E8F0'}}}}));detail.addRow(['统计类型','周别','节点','客户ID','客户姓名','变更内容','备注','时间','导出用户']);detail.getRow(1).font={bold:true};detail.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF1F5F9'}};['this','last'].forEach(wk=>{rows.forEach(r=>{(detailMap[wk][r.key]||[]).forEach(it=>detail.addRow([kindLabel,wk==='this'?'本周':'上周',r.label,it.cusId,it.name,`从【${it.previousNodeStatus||'—'}】到【${it.currentNodeStatus||'—'}】`,it.remark||'',it.createTime?formatDateTime(it.createTime):'',targetUid]))})});detail.columns=[{width:14},{width:10},{width:22},{width:24},{width:16},{width:32},{width:26},{width:20},{width:24}];detail.eachRow((row,rowNumber)=>row.eachCell(cell=>{cell.alignment={vertical:'middle',horizontal:rowNumber===1?'center':'left',wrapText:true};cell.border={top:{style:'thin',color:{argb:'FFE2E8F0'}},left:{style:'thin',color:{argb:'FFE2E8F0'}},bottom:{style:'thin',color:{argb:'FFE2E8F0'}},right:{style:'thin',color:{argb:'FFE2E8F0'}}}}));return wb.xlsx.writeBuffer()}
async function uploadBuffer({buffer,fileName}){const cloudPath=`exports/spa-stats/${Date.now()}-${Math.random().toString(36).slice(2,8)}-${fileName}`;const up=await uniCloud.uploadFile({cloudPath,fileContent:buffer});const fileID=up&&(up.fileID||up.fileId);let tempFileURL='';if(fileID&&uniCloud.getTempFileURL){const tempRes=await uniCloud.getTempFileURL({fileList:[fileID]});const first=(tempRes&&(tempRes.fileList||tempRes.tempFileList||[])[0])||{};tempFileURL=first.tempFileURL||first.tempFileUrl||first.download_url||''}return{fileID,cloudPath,tempFileURL}}
module.exports={async adminGetSpaStatsForUser(context,params={}){const uid=await getCurrentUid(context);if(!uid)return{errCode:'uni-id-check-token-failed',errMsg:'登录状态失效，请重新登录'};const targetUid=String(params.userId||'').trim();const kind=String(params.kind||'sales')==='recruit'?'recruit':'sales';if(!targetUid)return{errCode:'admin-invalid-user-id',errMsg:'用户ID不能为空'};const access=await ensureAccess({uid,targetUid});if(!access.ok)return{errCode:access.errCode,errMsg:access.errMsg};const {logs,cusMap}=await loadStats({targetUid,kind});return{errCode:0,errMsg:'',data:{logs,cusMap}}},async exportMySpaStatsExcel(context,params={}){const uid=await getCurrentUid(context);if(!uid)return{errCode:'uni-id-check-token-failed',errMsg:'登录状态失效，请重新登录'};const kind=String(params.kind||'sales')==='recruit'?'recruit':'sales';const targetUid=String(params.userId||uid).trim()||uid;const access=await ensureAccess({uid,targetUid});if(!access.ok)return{errCode:access.errCode,errMsg:access.errMsg};const {logs,cusMap}=await loadStats({targetUid,kind});const {rows,countMap,detailMap}=buildSummary({kind,logs,cusMap});const kindLabel=kind==='recruit'?'增员':'销售客户';const fileName=`${kindLabel}统计-${formatDateOnly(Date.now())}.xlsx`;const buffer=await makeBuffer({kind,targetUid,rows,countMap,detailMap});const uploadRes=await uploadBuffer({buffer,fileName});return{errCode:0,errMsg:'',data:{fileName,fileID:uploadRes.fileID,cloudPath:uploadRes.cloudPath,tempFileURL:uploadRes.tempFileURL,rowCount:rows.length,logCount:logs.length}}}}
